### ISSUE TITLE
[python-lxc] set_config_item() inserts empty value

### ISSUE THREAD

**Issue by googley** [lxc/lxc#1415]
```python
>>> import lxc
>>> c = lxc.Container('test')
>>> c.set_config_item('lxc.network.0.ipv4', ['192.168.1.1/24', '10.0.0.1/8'])
True
>>> c = lxc.Container('test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/Documents/git/.venv/lib/python3.5/site-packages/lxc/__init__.py", line 157, in __init__
    _lxc.Container.__init__(self, name)
RuntimeError: Container_init:lxc.c:531: error during init for container 'test'.
```

```bash
elie@ubuntu$ cat /var/lib/lxc/test/config
[...]
lxc.network.0.ipv4 =
lxc.network.0.ipv4 = 192.168.1.1/24
lxc.network.0.ipv4 = 10.0.0.1/8
```

Is there a workaround?

**Comment by stgraber** [comment]
The config above should be valid and it's not unreasonable for set_config_item to inject that empty value as that's how your reset the inheritance of a config key in an LXC config.

Any chance you can use one of the command line LXC tools with -l debug to get the LXC error which is being triggered here?

**Comment by googley** [comment]
```shell
elie@ubuntu$ lxc-start -l debug -n test
lxc-start: confile.c: config_network_ipv4: 835 Success - invalid ipv4 address:
lxc-start: parse.c: lxc_file_for_each_line: 57 Failed to parse config: lxc.network.0.ipv4 =

lxc-start: tools/lxc_start.c: main: 279 Failed to create lxc_container
```

**Comment by stgraber** [comment]
@brauner is that something you can take a look at when you have a minute? should be a reasonably straightforward fix since we have this handled for just about every other key.

**Comment by stgraber** [comment]
@googley what LXC version is that?

**Comment by brauner** [comment]
@stgraber, sure can do.

**Comment by googley** [comment]
@stgraber 2.0.5
