### ISSUE TITLE
read-after-free in do_lxcapi_start

### ISSUE THREAD

**Issue by flx42** [lxc/lxc#2218]
On master:
https://github.com/lxc/lxc/blob/19462d43e8e9744f08f127bfb5d5a9f08c1aafa9/src/lxc/lxccontainer.c#L1072
This seems to be a read-after-free (as reported by valgrind), since the handler was freed at the end of `__lxc_start`:
```
Breakpoint 1, lxc_free_handler (handler=handler@entry=0x62b2d0) at start.c:635
635     {
(gdb) bt
#0  lxc_free_handler (handler=handler@entry=0x62b2d0) at start.c:635
#1  0x00007ffff7b5e28a in lxc_fini (name=name@entry=0x60ae50 "ubuntu", handler=handler@entry=0x62b2d0) at start.c:1001
#2  0x00007ffff7b5e866 in __lxc_start (name=name@entry=0x60ae50 "ubuntu", handler=handler@entry=0x62b2d0, ops=ops@entry=0x7ffff7dd5840 <execute_start_ops>, data=data@entry=0x7fffffffc7e0, 
    lxcpath=lxcpath@entry=0x627ac0 "/home/fabecassis/.local/share/lxc", backgrounded=backgrounded@entry=false) at start.c:1931
#3  0x00007ffff7b6035c in lxc_execute (name=0x60ae50 "ubuntu", argv=argv@entry=0x7fffffffe278, quiet=quiet@entry=1, handler=handler@entry=0x62b2d0, lxcpath=0x627ac0 "/home/fabecassis/.local/share/lxc", 
    backgrounded=backgrounded@entry=false) at execute.c:131
#4  0x00007ffff7ba2113 in do_lxcapi_start (c=c@entry=0x627cf0, useinit=useinit@entry=1, argv=argv@entry=0x7fffffffe278) at lxccontainer.c:1069
#5  0x00007ffff7ba29ee in lxcapi_start (c=0x627cf0, useinit=1, argv=0x7fffffffe278) at lxccontainer.c:1105
#6  0x0000000000402705 in main (argc=<optimized out>, argv=<optimized out>) at tools/lxc_execute.c:241
```

 I don't have a patch for this one since I'm not sure what's the best way to fix it.

**Comment by brauner** [comment]
@flx42 I'll take a look if you want me to. :)
