### ISSUE TITLE
Crash when creating many privileged containers concurrently

### ISSUE THREAD

**Issue by ChrisMacNaughton** [lxc/lxc#2623]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04

# Issue description

There is a SIGSEGV crashing LXD when creating a lot of privileged containers concurrently

```
Sep 19 07:10:10 node-weyl lxd.daemon[63024]: fatal error: unexpected signal during runtime execution
Sep 19 07:10:10 node-weyl lxd.daemon[63024]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f7159e8daa5]
Sep 19 07:10:10 node-weyl lxd.daemon[63024]: runtime stack:
Sep 19 07:10:10 node-weyl lxd.daemon[63024]: runtime.throw(0x114236e, 0x2a)
Sep 19 07:10:10 node-weyl lxd.daemon[63024]: #011/build/lxd/parts/go/build/src/runtime/panic.go:608 +0x72
Sep 19 07:10:10 node-weyl lxd.daemon[63024]: runtime.sigpanic()
Sep 19 07:10:10 node-weyl lxd.daemon[63024]: #011/build/lxd/parts/go/build/src/runtime/signal_unix.go:374 +0x2f2
Sep 19 07:10:10 node-weyl lxd.daemon[63024]: goroutine 47891 [syscall]:
Sep 19 07:10:10 node-weyl lxd.daemon[63024]: runtime.cgocall(0xedb5e0, 0xc000fe3750, 0xc000fe3758)
Sep 19 07:10:10 node-weyl lxd.daemon[63024]: #011/build/lxd/parts/go/build/src/runtime/cgocall.go:128 +0x5e fp=0xc000fe3720 sp=0xc000fe36e8 pc=0x40e21e
Sep 19 07:10:10 node-weyl lxd.daemon[63024]: gopkg.in/lxc/go-lxc%2ev2._Cfunc_go_lxc_get_cgroup_item(0x7f7024000d60, 0x7f70240058b0, 0x0)
Sep 19 07:10:10 node-weyl lxd.daemon[63024]: #011_cgo_gotypes.go:643 +0x4e fp=0xc000fe3750 sp=0xc000fe3720 pc=0x928dce
Sep 19 07:10:10 node-weyl lxd.daemon[63024]: gopkg.in/lxc/go-lxc%2ev2.(*Container).cgroupItem.func2(0x7f7024000d60, 0x7f70240058b0, 0x7f70240058b0)
Sep 19 07:10:10 node-weyl lxd.daemon[63024]: #011/build/lxd/parts/lxd/go/src/gopkg.in/lxc/go-lxc.v2/container.go:780 +0x60 fp=0xc000fe3788 sp=0xc000fe3750 pc=0x938fe0
Sep 19 07:10:10 node-weyl lxd.daemon[63024]: gopkg.in/lxc/go-lxc%2ev2.(*Container).cgroupItem(0xc0013bf800, 0x1116079, 0xc, 0x0, 0x0, 0x0)
Sep 19 07:10:10 node-weyl lxd.daemon[63024]: #011/build/lxd/parts/lxd/go/src/gopkg.in/lxc/go-lxc.v2/container.go:780 +0x90 fp=0xc000fe37e0 sp=0xc000fe3788 pc=0x92f770
Sep 19 07:10:10 node-weyl lxd.daemon[63024]: gopkg.in/lxc/go-lxc%2ev2.(*Container).CgroupItem(0xc0013bf800, 0x1116079, 0xc, 0x0, 0x0, 0x0)
Sep 19 07:10:10 node-weyl lxd.daemon[63024]: #011/build/lxd/parts/lxd/go/src/gopkg.in/lxc/go-lxc.v2/container.go:805 +0x8a fp=0xc000fe3820 sp=0xc000fe37e0 pc=0x92fa2a
Sep 19 07:10:10 node-weyl lxd.daemon[63024]: main.(*containerLXC).CGroupGet(0xc00160bf00, 0x1116079, 0xc, 0x10000, 0xc000cc325a, 0x2, 0xc000cc32a0)
Sep 19 07:10:10 node-weyl lxd.daemon[63024]: #011/build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/container_lxc.go:3664 +0x8c fp=0xc000fe3868 sp=0xc000fe3820 pc=0xced1fc
Sep 19 07:10:10 node-weyl lxd.daemon[63024]: main.(*containerLXC).processesState(0xc00160bf00, 0xc0002cbbc0)
Sep 19 07:10:10 node-weyl lxd.daemon[63024]: #011/build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/container_lxc.go:6079 +0x39c fp=0xc000fe3938 sp=0xc000fe3868 pc=0xd083dc
Sep 19 07:10:10 node-weyl lxd.daemon[63024]: main.(*containerLXC).RenderState(0xc00160bf00, 0xc000226754, 0xe, 0x12e5b80)
Sep 19 07:10:10 node-weyl lxd.daemon[63024]: #011/build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/container_lxc.go:3144 +0x8d8 fp=0xc000fe3a10 sp=0xc000fe3938 pc=0xce7a78
Sep 19 07:10:10 node-weyl lxd.daemon[63024]: main.containerState(0xc0002d8340, 0xc001382100, 0x1109fee, 0x3)
Sep 19 07:10:10 node-weyl lxd.daemon[63024]: #011/build/lxd/parts/lxd/go/src/github.com/lxc/lxd/lxd/container_state.go:32 +0x196 fp=0xc000fe3aa0 sp=0xc000fe3a10 pc=0xd306d6
Sep 19 07:10:10 node-weyl lxd.daemon[63024]: main.(*Daemon).createCmd.func1(0x12c8200, 0xc0002a07e0, 0xc001382100)```

**Comment by ChrisMacNaughton** [comment]
This is causing failures in conjure-up when deploying OpenStack on LXD

**Comment by brauner** [comment]
Also, we fixed it. :)

**Comment by ryan-beisner** [comment]
@brauner can you please link the related fixes here?  Many thanks!
