### ISSUE TITLE
Unable to set multiple network devices using Python bindings during container creation

### ISSUE THREAD

**Issue by BruceMty** [lxc/lxc#2853]
# Brief description
Crash when attempting to set multiple network devices using Python bindings during container creation.

# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of
   * `lxc-start --version`: 3.0.3
   * `lxc-checkconfig`

Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-4.15.0-45-generic
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points: 
/sys/fs/cgroup/systemd
/sys/fs/cgroup/devices
/sys/fs/cgroup/blkio
/sys/fs/cgroup/rdma
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/memory
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/pids
/sys/fs/cgroup/hugetlb
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/freezer

Cgroup v2 mount points: 
/sys/fs/cgroup/unified

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, not loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, not loaded
CONFIG_NF_NAT_IPV4: enabled, not loaded
CONFIG_NF_NAT_IPV6: enabled, not loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, not loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: 

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

   * `uname -a`

Linux bruce6556 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

   * `cat /proc/self/cgroup`

12:freezer:/user/bdallen/0
11:cpuset:/
10:perf_event:/
9:hugetlb:/
8:pids:/user.slice/user-1000.slice/user@1000.service
7:net_cls,net_prio:/
6:memory:/user/bdallen/0
5:cpu,cpuacct:/user.slice
4:rdma:/
3:blkio:/user.slice
2:devices:/user.slice
1:name=systemd:/user.slice/user-1000.slice/user@1000.service/gnome-terminal-server.service
0::/user.slice/user-1000.slice/user@1000.service/gnome-terminal-server.service

   * `cat /proc/1/mounts`

sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=4039308k,nr_inodes=1009827,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=813912k,mode=755 0 0
/dev/sda1 / ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/unified cgroup2 rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/rdma cgroup rw,nosuid,nodev,noexec,relatime,rdma 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,clone_children 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=32,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=16475 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
configfs /sys/kernel/config configfs rw,relatime 0 0
tracefs /sys/kernel/debug/tracing tracefs rw,relatime 0 0
/dev/loop9 /snap/gnome-system-monitor/51 squashfs ro,nodev,relatime 0 0
/dev/loop0 /snap/gnome-calculator/180 squashfs ro,nodev,relatime 0 0
/dev/loop6 /snap/gnome-3-26-1604/74 squashfs ro,nodev,relatime 0 0
/dev/loop2 /snap/core/6350 squashfs ro,nodev,relatime 0 0
/dev/loop4 /snap/gnome-3-26-1604/70 squashfs ro,nodev,relatime 0 0
/dev/loop3 /snap/gnome-characters/124 squashfs ro,nodev,relatime 0 0
/dev/loop1 /snap/core/6259 squashfs ro,nodev,relatime 0 0
/dev/loop15 /snap/gnome-system-monitor/57 squashfs ro,nodev,relatime 0 0
/dev/loop5 /snap/gnome-calculator/238 squashfs ro,nodev,relatime 0 0
/dev/loop7 /snap/gnome-logs/37 squashfs ro,nodev,relatime 0 0
/dev/loop8 /snap/gnome-calculator/260 squashfs ro,nodev,relatime 0 0
/dev/loop11 /snap/gnome-characters/103 squashfs ro,nodev,relatime 0 0
/dev/loop12 /snap/gnome-logs/45 squashfs ro,nodev,relatime 0 0
/dev/loop13 /snap/gtk-common-themes/818 squashfs ro,nodev,relatime 0 0
/dev/loop16 /snap/gtk-common-themes/808 squashfs ro,nodev,relatime 0 0
/dev/loop17 /snap/gnome-characters/139 squashfs ro,nodev,relatime 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,relatime 0 0
lxcfs /var/lib/lxcfs fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
tmpfs /run/user/121 tmpfs rw,nosuid,nodev,relatime,size=813908k,mode=700,uid=121,gid=125 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=813908k,mode=700,uid=1000,gid=1000 0 0
gvfsd-fuse /run/user/1000/gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0
tmpfs /run/snapd/ns tmpfs rw,nosuid,noexec,relatime,size=813912k,mode=755 0 0
nsfs /run/snapd/ns/gnome-system-monitor.mnt nsfs rw 0 0
/dev/loop18 /snap/gtk-common-themes/1122 squashfs ro,nodev,relatime 0 0
/dev/loop19 /snap/gnome-3-26-1604/78 squashfs ro,nodev,relatime 0 0
/dev/loop14 /snap/core/6405 squashfs ro,nodev,relatime 0 0

# Issue description
Crashes when attempting to set up second network device when using Ubuntu 18.

Note that the network device sets up fine when using Ubuntu 16.

# Steps to reproduce

1. Create two bridge devices:

        sudo brctl addbr bridge0; sudo brctl addbr bridge1

2. Configure your target OS, `xenial` or `bionic`, in the demo program, line 18.

3. Run the demo program, which attempts to create and start a container with two network devices:

        #!/usr/bin/env python3
        # ref. https://linuxcontainers.org/lxc/documentation/
        # requires: apt install python3-lxc
        #
        # setup: Create two bridge devices:
        #        "sudo brctl addbr bridge0; sudo brctl addbr bridge1"
        #
        # teardown: To destroy container:
        #           "sudo lxc-stop -n C1; sudo lxc-destroy -n C1"
        #           Remove the two bridge devices:
        #           "sudo brctl delbr bridge0; sudo brctl delbr bridge1"
        
        import lxc
        import sys
        
        container="C1"
        
        #target="xenial" # Ubuntu 16
        target="bionic" # Ubuntu 18
        
        # for Ubuntu 18 use "bionic", for Ubuntu 16 use "xenial"
        create_params = {"dist": "ubuntu", "release": target, "arch": "amd64"}
        
        # how to clean up
        print("To clean up type: 'sudo lxc-stop -n %s; sudo lxc-destroy -n %s'"%(
                                                             container, container))
        
        # create the container
        print("Creating container %s..."%container)
        c = lxc.Container(container)
        
        # skip if defined
        if c.defined:
            print("container %s already exists.  Aborting."%container)
            sys.exit(1)
        
        # create container rootfs
        success = c.create("download", lxc.LXC_CREATE_QUIET, create_params)
        if not success:
            print("Error creating container %s."%container, file=sys.stderr)
            sys.exit(1)
        
        # set up network device [0]
        c.network[0].type = "veth"
        c.network[0].flags = "up"
        c.network[0].link = "bridge0"
        if target=="xenial":
            c.network[0].ipv4 = "10.0.1.0/24"
        elif target=="bionic":
            c.network[0].ipv4_address = "10.0.1.0/24"
        else:
            raise RuntimeError("configuration error")
        
        # set up network device [1]
        c.network[1].type = "veth"
        c.network[1].flags = "up"
        c.network[1].link = "bridge1"
        if target=="xenial":
            c.network[1].ipv4 = "10.0.0.1/24"
        elif target=="bionic":
            c.network[1].ipv4_address = "10.0.1.1/24"
        else:
            raise RuntimeError("configuration error")
        
        # start the container
        success = c.start()
        if not success:
            print("Error starting container %s."%container, file=sys.stderr)
            sys.exit(1)

4. Observe output

Run the demo: `sudo ./demo.py`

When it works (Ubuntu 16) it creates the container with the two network devices correctly configured.  Type `sudo lxc-ls -f` to see success:

    NAME    STATE   AUTOSTART GROUPS IPV4               IPV6 
    C1      RUNNING 0         -      10.0.0.1, 10.0.1.0 -    

When it fails (Ubuntu 18) it crashes with `IndexError: list index out of range`:

    Creating container C1...
    Traceback (most recent call last):
      File "./zic2.py", line 39, in <module>
        c.network[1].type = "veth"
      File "/usr/lib/python3/dist-packages/lxc/__init__.py", line 122, in __getitem__
        raise IndexError("list index out of range")
    IndexError: list index out of range

5. Cleanup

Remove the container and the two Bridge devices:

        sudo lxc-destroy -n C1
        sudo brctl delbr bridge0; sudo brctl delbr bridge1

# Recommended action
I don't mind a hack to get by.  Maybe something to initialize multiple network entries.  Or maybe a configure file that puts in two dummy network entries so that my code can set the values as needed.

# Information to attach

 - [ ] any relevant kernel output (`dmesg`)
 - [ ] container log (The <log> file from running `lxc-start -n <c> -l <log> -o DEBUG`)
 - [ ] the containers configuration file

**Comment by dnegreira** [comment]
As far as I can see you have an error in your network configuration: 

```
c.network[1].ipv4 = "10.0.0.1/24"
c.network[1].ipv4_address = "10.0.1.1/24"
```

Does it still happen if you fix this?

**Comment by BruceMty** [comment]
Yes, the error still happens when I fix the IP to the intended value:

    if target=="xenial":
        c.network[1].ipv4 = "10.0.0.1/24"
    elif target=="bionic":
        c.network[1].ipv4_address = "10.0.0.1/24"

The use of `ipv4` in Ubuntu 16 vs `ipv4_address` in Ubuntu 18 is intentional.

**Comment by BruceMty** [comment]
It looks to me like the newer version of LXC is unable to allocate additional networks while the older version of LXC is able to.
