### ISSUE TITLE
Supposedly hitting some imposed system limit after upgrading from LXC 2.0 to 3.0

### ISSUE THREAD

**Issue by agis** [lxc/lxc#3494]
# Required information

 * Distribution: Debian
 * Distribution version: Debian Buster (10)
 * The output of
   * `lxc-start --version`: `3.0.3`
   * `lxc-checkconfig`: [gist](https://gist.github.com/agis/dfb6e7d3e9b20ea50fb8c980ffc1ffff)
   * `uname -a`: `Linux [REDACTED] 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linu`
   * `cat /proc/self/cgroup`: [gist](https://gist.github.com/agis/dfb6e7d3e9b20ea50fb8c980ffc1ffff)
   * `cat /proc/1/mounts`: [gist](https://gist.github.com/agis/dfb6e7d3e9b20ea50fb8c980ffc1ffff)

# Issue description

_Disclaimer: I don't know if this is an LXC-related issue; it could very well be due to a systemd or a Kernel-related change._

We have an EC2 instance with 96 logical cores (48 physical) that, until recently was running in Debian Stretch and hence with lxc 2.0.7. We spawn 48 containers that are clones of a central one (which run a Buster image) and each of them runs a set of services (MariaDB, ElasticSearch, Redis, sshd etc.).

After we upgraded the host instance to Debian Buster (and hence lxc to 3.0.3), we started noticing ElasticSearch in some LXCs, throwing some errors like this:

```
[2020-07-20T17:29:44,749][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [foo] fatal error in thread [elasticsearch[foo][refresh][T#1]], exiting
java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method) ~[?:1.8.0_222]
        at java.lang.Thread.start(Thread.java:717) ~[?:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957) ~[?:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1025) ~[?:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) ~[?:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_222]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```

Now, after searching around I've stumbled onto [this post](https://www.elastic.co/blog/we-are-out-of-memory-systemd-process-limits) which outlines some possible reasons, almost all of them related to some resource limit imposed by the system (systemd? kernel?). Unfortunately I've tried all of them (in the host) without any luck:

- setting `-XX:ThreadSafetyMargin=0` in JVM
- bumped max user processes (`ulimit -u`) to 772262
- bumped `/proc/sys/kernel/pid_max` to 150000
- bumped `/proc/sys/kernel/threads-max` to 1544524
- bumped systemd's `DefaultTasksMax` to 50000 (also lxc.service `TasksMax`)

Do you have perhaps anything in mind that changed between LXC 2.0 until 3.0, that could impose some global limits? One thing would be the apparmor profile, but we've set this to `unconfined`.

Thanks in advance!

# Steps to reproduce

N/A

# Information to attach

 - [x] any relevant kernel output (`dmesg`): [gist](https://gist.github.com/agis/dfb6e7d3e9b20ea50fb8c980ffc1ffff)
 - [ ] container log (The <log> file from running `lxc-start -n <c> -l TRACE -o <logfile> `)
 - [x] the containers configuration file: [gist](https://gist.github.com/agis/dfb6e7d3e9b20ea50fb8c980ffc1ffff)

**Comment by brauner** [comment]
What does `ulimit -a` from within the container show?

**Comment by agis** [comment]
> What does `ulimit -a` from within the container show?

```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 772262
max locked memory       (kbytes, -l) 65536
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 772262
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

-----------------------------

I should also mention that the total number of tasks in the host (i.e. due to all containers) when all containers are busy, is in the range of 6-8k (each container spawns ~160 tasks):

```
$ ps -eLF | wc -l
7060
```

**Comment by agis** [comment]
Another important clue I forgot to outline, is that we pin LXCs to specific cores - each container is pinned to two sibling cores. I verified the the the pinning works using `stress` from inside containers.

**Comment by brauner** [comment]
Can you show the `pids.max` value for the `pids` cgroup of the container is running in?

**Comment by agis** [comment]
> Can you show the `pids.max` value for the `pids` cgroup of the container is running in?

All containers have this set to `max`:

```
$ cat /sys/fs/cgroup/pids/lxc/foo*/pids.max | uniq
max
```

I noticed that by decreasing the number of containers (from 48 to 30), the issue goes away. That's why I suspect it's some kind of global limit (i.e. imposed on the host).

**Comment by agis** [comment]
Not sure if this is relevant but I also notice the following difference between Buster (where the issue happens) and Stretch (where it does not):

`/etc/lxc/default.conf` in Buster:
```
lxc.net.0.type = empty
lxc.apparmor.profile = generated
lxc.apparmor.allow_nesting = 1
```

while `/etc/lxc/default.conf` in Stretch:
```
lxc.network.type = empty
```

**Comment by brauner** [comment]
We have a production guide for LXD:
https://linuxcontainers.org/lxd/docs/master/production-setup
Can you apply these defaults and see whether the issue is reproducible?

**Comment by agis** [comment]
Unfortunately didn't do the trick either. I performed the changes and rebooted the instance without any luck.

```
$ cat /etc/security/limits.d/ec2_lxc.conf 
# See https://linuxcontainers.org/lxd/docs/master/production-setup
*       soft    nofile  1048576
*       hard    nofile  1048576
root    soft    nofile  1048576
root    hard    nofile  1048576
*       soft    memlock         unlimited
*       hard    memlock         unlimited
```

```
$ cat /etc/sysctl.d/ec2_lxc.conf 
# See https://linuxcontainers.org/lxd/docs/master/production-setup
fs.inotify.max_queued_events = 1048576
fs.inotify.max_user_instances = 1048576 
fs.inotify.max_user_watches = 1048576
vm.max_map_count = 262144
kernel.dmesg_restrict = 1
net.ipv4.neigh.default.gc_thresh3 = 8192
net.ipv6.neigh.default.gc_thresh3 = 8192
net.core.bpf_jit_limit = 3000000000
kernel.keys.maxkeys = 2000
kernel.keys.maxbytes = 2000000
fs.aio-max-nr = 524288
```

Note: I verified all of the above were correctly set using `sysctl -a`.

**Comment by brauner** [comment]
So, I wonder if you're really OOMing. What's the default memory size for a thread in the JVM? If it's e.g. 8 mb and you're creating thousands of threads you might run out of memory

**Comment by agis** [comment]
Well the machine has 190GB of memory and when all 48 containers are busy, peak used memory is about 150GB, so I'd say it's very unlikely that we're OOMing. Also, dmesg shows nothing related.

**Comment by brauner** [comment]
> Well the machine has 190GB of memory and when all 48 containers are busy, peak used memory is about 150GB, so I'd say it's very unlikely that we're OOMing. Also, dmesg shows nothing related.

Sure, but is the container somehow limited by e.g. systemd through the memory cgroup?

**Comment by mihalicyn** [comment]
No new replies since 2020. Closing. Feel free to reopen if it's still actual and any help from my side is needed.
