### ISSUE TITLE
start.c: lxc_spawn blocks at recv for devpts_fd

### ISSUE THREAD

**Issue by r10r** [lxc/lxc#3549]
Required information

 * Distribution: debian
 * Distribution version: 10.6
 * LXC version: master
 * Kernel 5.8.10-1 

# Issue description

While testing my crio-lxc fork against lxc/master I noticed that container startup simply blocks
Container startup works fine with version 4.0.4.

I traced it down to the following line :

https://github.com/lxc/lxc/blob/11d123becb02a86c51baf0124fa21f79a0b6326b/src/lxc/start.c#L1956

When I comment the line startup continues.

The line was introduced in  https://github.com/lxc/lxc/commit/f797f05e6e600e0c1ac8778ce750a81e6830778d

Devices for the OCI spec are created in the hook `lxc.hook.mount`

Since stdio should be inherited from the calling process (`conmon` from `cri-o`) I  set `lxc.console.path=none` 

The container config is:

```
lxc.log.file = /var/log/crio-lxc.log
lxc.log.level = TRACE
lxc.rootfs.path = /var/lib/containers/storage/overlay/b8f86a50965360093c6a729d1ed3230a93e3ee1fdf85a1cbf188146d6437e05e/merged
lxc.rootfs.managed = 0
lxc.rootfs.options = ro
lxc.hook.mount = /usr/local/bin/crio-lxc-hook
lxc.environment = PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
lxc.environment = CRIO_LXC_STATE=created
lxc.init.cmd = /.crio-lxc/init
lxc.mount.entry = proc /var/lib/containers/storage/overlay/b8f86a50965360093c6a729d1ed3230a93e3ee1fdf85a1cbf188146d6437e05e/merged/proc proc nosuid,noexec,nodev,create=dir
lxc.mount.entry = tmpfs /var/lib/containers/storage/overlay/b8f86a50965360093c6a729d1ed3230a93e3ee1fdf85a1cbf188146d6437e05e/merged/dev tmpfs nosuid,strictatime,mode=755,size=65536k,create=dir
lxc.mount.entry = devpts /var/lib/containers/storage/overlay/b8f86a50965360093c6a729d1ed3230a93e3ee1fdf85a1cbf188146d6437e05e/merged/dev/pts devpts nosuid,noexec,newinstance,ptmxmode=0666,mode=0620,gid=5,create=dir
lxc.mount.entry = mqueue /var/lib/containers/storage/overlay/b8f86a50965360093c6a729d1ed3230a93e3ee1fdf85a1cbf188146d6437e05e/merged/dev/mqueue mqueue nosuid,noexec,nodev,create=dir
lxc.mount.entry = sysfs /var/lib/containers/storage/overlay/b8f86a50965360093c6a729d1ed3230a93e3ee1fdf85a1cbf188146d6437e05e/merged/sys sysfs nosuid,noexec,nodev,ro,create=dir
lxc.mount.entry = /var/run/containers/storage/overlay-containers/e4b7453c5e09a7f0f340e3b6c2dd7dcb7dbc76e888c57b243a98996ca9baf98f/userdata/resolv.conf /var/lib/containers/storage/overlay/b8f86a50965360093c6a729d1ed3230a93e3ee1fdf85a1cbf188146d6437e05e/merged/etc/resolv.conf bind ro,bind,nodev,nosuid,noexec,create=file
lxc.mount.entry = /var/run/containers/storage/overlay-containers/e4b7453c5e09a7f0f340e3b6c2dd7dcb7dbc76e888c57b243a98996ca9baf98f/userdata/shm /var/lib/containers/storage/overlay/b8f86a50965360093c6a729d1ed3230a93e3ee1fdf85a1cbf188146d6437e05e/merged/dev/shm bind rw,bind,create=dir
lxc.mount.entry = /var/run/containers/storage/overlay-containers/e4b7453c5e09a7f0f340e3b6c2dd7dcb7dbc76e888c57b243a98996ca9baf98f/userdata/hostname /var/lib/containers/storage/overlay/b8f86a50965360093c6a729d1ed3230a93e3ee1fdf85a1cbf188146d6437e05e/merged/etc/hostname bind ro,bind,nodev,nosuid,noexec,create=file
lxc.mount.entry = /run/crio-lxc/e4b7453c5e09a7f0f340e3b6c2dd7dcb7dbc76e888c57b243a98996ca9baf98f/.crio-lxc /var/lib/containers/storage/overlay/b8f86a50965360093c6a729d1ed3230a93e3ee1fdf85a1cbf188146d6437e05e/merged/.crio-lxc bind bind,ro,create=dir
lxc.mount.entry = /usr/local/bin/crio-lxc-init /var/lib/containers/storage/overlay/b8f86a50965360093c6a729d1ed3230a93e3ee1fdf85a1cbf188146d6437e05e/merged/.crio-lxc/init bind bind,ro,create=file
lxc.uts.name = k8s-cluster2-controller
lxc.hook.version = 1
lxc.namespace.share.ipc = /var/run/ipcns/6a803c19-ee69-4fa6-b400-a420a8139e16
lxc.namespace.share.uts = /var/run/utsns/6a803c19-ee69-4fa6-b400-a420a8139e16
lxc.namespace.clone = pid mnt
lxc.apparmor.profile = unconfined
lxc.proc.oom_score_adj = -998
lxc.seccomp.profile = /run/crio-lxc/e4b7453c5e09a7f0f340e3b6c2dd7dcb7dbc76e888c57b243a98996ca9baf98f/seccomp.conf
lxc.ephemeral = 0
lxc.cap.keep = chown dac_override fsetid fowner setgid setuid setpcap net_bind_service kill
lxc.init.uid = 0
lxc.init.gid = 0
lxc.cgroup.dir.container = kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod9da3b2a14682e1fb23be3c2492753207.slice/crio-e4b7453c5e09a7f0f340e3b6c2dd7dcb7dbc76e888c57b243a98996ca9baf98f.scope
lxc.cgroup.dir.monitor = crio-lxc-monitor.slice/e4b7453c5e09a7f0f340e3b6c2dd7dcb7dbc76e888c57b243a98996ca9baf98f.scope
lxc.cgroup.relative = 0
lxc.autodev = 0
lxc.cgroup2.devices.allow = c 1:3 rwm
lxc.cgroup2.devices.allow = c 1:5 rwm
lxc.cgroup2.devices.allow = c 1:7 rwm
lxc.cgroup2.devices.allow = c 1:8 rwm
lxc.cgroup2.devices.allow = c 1:9 rwm
lxc.cgroup2.devices.allow = c 5:0 rwm
lxc.cgroup2.devices.allow = c 5:2 rwm
lxc.console.path = none
```

gdb backtrace 
```
#0  0x00007fc1e88437b4 in __libc_recvmsg (fd=fd@entry=13, msg=msg@entry=0x7ffcc2e97720, flags=flags@entry=1073741824) at ../sysdeps/unix/sysv/linux/recvmsg.c:28
#1  0x00007fc1e8928d06 in lxc_abstract_unix_recv_fds_iov (iovlen=1, iov=0x7ffcc2e97710, num_recvfds=<optimized out>, recvfds=0x55aef4d86ed8, fd=13) at af_unix.c:193
#2  lxc_abstract_unix_recv_fds (fd=13, recvfds=0x55aef4d86ed8, num_recvfds=num_recvfds@entry=1, data=data@entry=0x0, size=size@entry=0) at af_unix.c:224
#3  0x00007fc1e89801b2 in lxc_spawn (handler=0x55aef4d8a1d0) at start.c:1956
#4  0x00007fc1e898078d in __lxc_start (handler=handler@entry=0x55aef4d8a1d0, ops=ops@entry=0x7fc1e89e1ee0 <start_ops>, data=data@entry=0x7ffcc2e97f08, lxcpath=lxcpath@entry=0x55aef4d84b60 "/run/crio-lxc", 
    daemonize=daemonize@entry=false, error_num=error_num@entry=0x55aef4d84960) at start.c:2074
#5  0x00007fc1e8980e0c in lxc_start (argv=argv@entry=0x55aef4d8a330, handler=handler@entry=0x55aef4d8a1d0, lxcpath=0x55aef4d84b60 "/run/crio-lxc", daemonize=<optimized out>, 
    error_num=error_num@entry=0x55aef4d84960) at start.c:2191
#6  0x00007fc1e896583f in do_lxcapi_start (c=0x55aef4d84920, useinit=0, argv=0x55aef4d8a330) at lxccontainer.c:1106
#7  0x00007fc1e8966011 in lxcapi_start (c=0x55aef4d84920, useinit=0, argv=0x0) at lxccontainer.c:1140
#8  0x000055aef4296368 in main ()
```

**Comment by r10r** [comment]
@brauner  Is there something missing in the configuration?

**Comment by brauner** [comment]
Do you have a trace log for the container?

**Comment by r10r** [comment]
No, i've deleted it. But I can reproduce it. Shall I test it with the latest changes ?

**Comment by r10r** [comment]
I've cherry picked https://github.com/brauner/lxc/commit/fbfe5c8208fd8304ee74b2e297585c64a0d6bd81
but startup still blocks. Config and trace log. are attached.

```
Rubens-MBP-2:~ ruben$ grep "Sent devpts file descriptor" 3549.lxc.trace.log 
Rubens-MBP-2:~ ruben$ grep "Received devpts file descriptor" 3549.lxc.trace.log 
Rubens-MBP-2:~ ruben$ grep devpts 3549.lxc.trace.log 
lxc 87af6e6345a20992093a8617d75603a190910c9a0198a1b470b439acf3c920b7 20201019105130.763 DEBUG    conf - conf.c:mount_entry:1990 - Mounted "devpts" on "/usr/local/lib/lxc/rootfs//dev/pts" with filesystem type "devpts"
lxc 87af6e6345a20992093a8617d75603a190910c9a0198a1b470b439acf3c920b7 20201019105130.769 DEBUG    conf - conf.c:lxc_setup_devpts:1492 - No new devpts instance will be mounted since no pts devices are requested
```

[3549.trace.config.txt](https://github.com/lxc/lxc/files/5401287/3549.trace.config.txt)
[3549.lxc.trace.log](https://github.com/lxc/lxc/files/5401282/3549.lxc.trace.log)

**Comment by r10r** [comment]
I did a full rebuild from master - unfortunately startup is still blocking. Same output as in https://github.com/lxc/lxc/issues/3549#issuecomment-712066304

**Comment by r10r** [comment]
@stgraber Can you please reopen the issue - thanks!

**Comment by r10r** [comment]
@brauner Can I send you some additional information ? Just tell me If I should test against your development branches.
If you add more TRACE output for debugging I'll send you the logs as fast as possible ...

If you want to test with the crio-lxc fork yourself I can prepare a release from my development branch.
But this will most likely take more time.  I'm currently investigating remaining conformance test failures  with k8s and crio-lxc,
which is a bit time consuming.

**Comment by brauner** [comment]
@r10r https://github.com/lxc/lxc/pull/3558 should fix it. I now know where this issue comes from.

**Comment by brauner** [comment]
Thank you for providing the logs!
