### ISSUE TITLE
ASan seems to report an ODR violation

### ISSUE THREAD

**Issue by evverx** [lxc/lxc#3757]
Trying to figure out how `lxc-exercise` works, I accidentally ran a couple of tests under ASan. They failed with
```
$ sudo ./src/tests/lxc-test-utils
=================================================================
==2501128==ERROR: AddressSanitizer: odr-violation (0x55b71bf2a420):
  [1] size=32 'lxc_log_category_af_unix' ../lxc/af_unix.c:29:1
  [2] size=32 'lxc_log_category_af_unix' af_unix.c:29:1
These globals were registered at these points:
  [1]:
    #0 0x7fa957384cc8  (/lib64/libasan.so.6+0x37cc8)
    #1 0x55b71bc62792 in _sub_I_00099_1 (/home/vagrant/lxc/src/tests/.libs/lt-lxc-test-utils+0x266792)
    #2 0x55b71be93a0c in __libc_csu_init (/home/vagrant/lxc/src/tests/.libs/lt-lxc-test-utils+0x497a0c)

  [2]:
    #0 0x7fa957384cc8  (/lib64/libasan.so.6+0x37cc8)
    #1 0x7fa956cf5ecb in _sub_I_00099_1 (/home/vagrant/lxc/src/lxc/.libs/liblxc.so.1+0x2d7ecb)
    #2 0x7fa957d3d801 in call_init.part.0 (/lib64/ld-linux-x86-64.so.2+0x11801)
```
As far as I can tell, this happens because `af_unix.c` is included in both `liblxc_la_SOURCES` and `lxc_test_utils_SOURCES` and `liblxc` along with `af_unix.o` are linked into `lxc-test-utils`.

It can be reproduced by compiling lxc with ASan and running `lxc-test-utils` (or any other binary like `lxc-ls`)
```
sed -i 's/-Wl,-no-undefined *\\/\\/' src/lxc/Makefile.am
./autogen.sh
CFLAGS="-O1 -fno-omit-frame-pointer -g -fsanitize=address,undefined -fsanitize-address-use-after-scope" ./configure --enable-tests
make -j$(nproc)
./src/tests/lxc-test-utils
```

**Comment by mihalicyn** [comment]
Yep, it can be that we violate ODR (one definition rule), unfortunately.
Recently, we have landed a change https://github.com/lxc/lxc/pull/4401 that can improve situation, but it's still worth paying attention to this.

Sorry for so long delay and thanks for your report!
