### ISSUE TITLE
lxcapi_createl seems to crash without templates

### ISSUE THREAD

**Issue by evverx** [lxc/lxc#3782]
It seems all the tests where `lxcapi_createl` is called are run after the "busybox" template has been installed with `make install` (which is probably why it has never crashed on Jenkins). Without the template `lxcapi_createl` crashes with
```
$ ./src/tests/lxc-test-console
lxccontainer.c:1927:8: runtime error: member access within null pointer of type 'struct lxc_conf'
AddressSanitizer:DEADLYSIGNAL
=================================================================
==370477==ERROR: AddressSanitizer: SEGV on unknown address 0x0000000031f8 (pc 0x7fccf3242a6d bp 0x7ffe9322db00 sp 0x7ffe9322d840 T0)
==370477==The signal is caused by a READ memory access.
    #0 0x7fccf3242a6d in do_lxcapi_create /home/vagrant/lxc/src/lxc/lxccontainer.c:1927
    #1 0x7fccf3246075 in lxcapi_createl /home/vagrant/lxc/src/lxc/lxccontainer.c:2184
    #2 0x557e905a339d in test_console /home/vagrant/lxc/src/tests/console.c:152
    #3 0x557e905a3938 in main /home/vagrant/lxc/src/tests/console.c:186
    #4 0x7fccf21b1081 in __libc_start_main (/lib64/libc.so.6+0x27081)
    #5 0x557e905a1a6d in _start (/home/vagrant/lxc/src/tests/.libs/lt-lxc-test-console+0x3a6d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/vagrant/lxc/src/lxc/lxccontainer.c:1927 in do_lxcapi_create
==370477==ABORTING
```

**Comment by brauner** [comment]
Ah, I see the issue.
