### ISSUE TITLE
There seems to be a memory leak in lxc_clone

### ISSUE THREAD

**Issue by evverx** [lxc/lxc#3789]
It was discovered in https://github.com/lxc/lxc/pull/3787
```
2021-04-15T11:17:56.1831990Z =================================================================
2021-04-15T11:17:56.1842895Z ==64316==ERROR: LeakSanitizer: detected memory leaks
2021-04-15T11:17:56.1843301Z 
2021-04-15T11:17:56.1843713Z Direct leak of 8388608 byte(s) in 1 object(s) allocated from:
2021-04-15T11:17:56.1845059Z     #0 0x7f812e73bbc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
2021-04-15T11:17:56.1846372Z     #1 0x7f812e06a4b1 in lxc_clone /home/runner/work/lxc/lxc/src/lxc/process_utils.c:152
2021-04-15T11:17:56.1847094Z     #2 0x7f812ded8be0 in userns_exec_full /home/runner/work/lxc/lxc/src/lxc/conf.c:4444
2021-04-15T11:17:56.1847904Z     #3 0x7f812dfd2dbf in do_destroy_container /home/runner/work/lxc/lxc/src/lxc/lxccontainer.c:2910
2021-04-15T11:17:56.1848742Z     #4 0x7f812dfd4572 in container_destroy /home/runner/work/lxc/lxc/src/lxc/lxccontainer.c:2997
2021-04-15T11:17:56.1849709Z     #5 0x7f812dfd5e8c in do_lxcapi_destroy /home/runner/work/lxc/lxc/src/lxc/lxccontainer.c:3096
2021-04-15T11:17:56.1850508Z     #6 0x7f812dfd6094 in lxcapi_destroy /home/runner/work/lxc/lxc/src/lxc/lxccontainer.c:3099
2021-04-15T11:17:56.1851180Z     #7 0x559fc219ae8a in do_destroy tools/lxc_destroy.c:108
2021-04-15T11:17:56.1851728Z     #8 0x559fc219c9ea in main tools/lxc_destroy.c:252
2021-04-15T11:17:56.1852580Z     #9 0x7f812ce7a0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
2021-04-15T11:17:56.1852998Z 
2021-04-15T11:17:56.1853408Z Direct leak of 8388608 byte(s) in 1 object(s) allocated from:
2021-04-15T11:17:56.1854242Z     #0 0x7f812e73bbc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
2021-04-15T11:17:56.1854969Z     #1 0x7f812e06a4b1 in lxc_clone /home/runner/work/lxc/lxc/src/lxc/process_utils.c:152
2021-04-15T11:17:56.1855680Z     #2 0x7f812ded8be0 in userns_exec_full /home/runner/work/lxc/lxc/src/lxc/conf.c:4444
2021-04-15T11:17:56.1866471Z     #3 0x7f812dfd52fa in container_destroy /home/runner/work/lxc/lxc/src/lxc/lxccontainer.c:3057
2021-04-15T11:17:56.1867317Z     #4 0x7f812dfd5e8c in do_lxcapi_destroy /home/runner/work/lxc/lxc/src/lxc/lxccontainer.c:3096
2021-04-15T11:17:56.1868122Z     #5 0x7f812dfd6094 in lxcapi_destroy /home/runner/work/lxc/lxc/src/lxc/lxccontainer.c:3099
2021-04-15T11:17:56.1868794Z     #6 0x559fc219ae8a in do_destroy tools/lxc_destroy.c:108
2021-04-15T11:17:56.1869344Z     #7 0x559fc219c9ea in main tools/lxc_destroy.c:252
2021-04-15T11:17:56.1870339Z     #8 0x7f812ce7a0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
2021-04-15T11:17:56.1870759Z 
2021-04-15T11:17:56.1871248Z SUMMARY: AddressSanitizer: 16777216 byte(s) leaked in 2 allocation(s).
```

**Comment by brauner** [comment]
Thanks for the report! Can you try https://github.com/lxc/lxc/pull/3790, please?
