### ISSUE TITLE
There seems to be a memory leak in lxc_cmd_console_log

### ISSUE THREAD

**Issue by evverx** [lxc/lxc#3796]
It was discovered in https://github.com/lxc/lxc/pull/3787
```
2021-04-17T10:31:44.6272361Z + timeout 10m /usr/bin/lxc-test-console-log
2021-04-17T10:31:44.6281983Z + tee /tmp/tmp.TIZPiR4RQb
2021-04-17T10:31:53.1213128Z 
2021-04-17T10:31:53.1213747Z =================================================================
2021-04-17T10:31:53.1214229Z ==74884==ERROR: LeakSanitizer: detected memory leaks
2021-04-17T10:31:53.1214581Z 
2021-04-17T10:31:53.1214985Z Direct leak of 48 byte(s) in 1 object(s) allocated from:
2021-04-17T10:31:53.1218723Z     #0 0x559e300fa2b2 in calloc (/usr/bin/lxc-test-console-log+0x962b2)
2021-04-17T10:31:53.1220007Z     #1 0x7ff07f05d0f8 in lxc_cmd_rsp_recv /home/runner/work/lxc/lxc/src/lxc/commands.c:289:12
2021-04-17T10:31:53.1220878Z     #2 0x7ff07f04fdc7 in lxc_cmd /home/runner/work/lxc/lxc/src/lxc/commands.c:513:8
2021-04-17T10:31:53.1221604Z     #3 0x7ff07f0573ed in lxc_cmd_console_log /home/runner/work/lxc/lxc/src/lxc/commands.c:1448:8
2021-04-17T10:31:53.1222631Z     #4 0x7ff07f1c6cf2 in do_lxcapi_console_log /home/runner/work/lxc/lxc/src/lxc/lxccontainer.c:581:8
2021-04-17T10:31:53.1223692Z     #5 0x7ff07f195137 in lxcapi_console_log /home/runner/work/lxc/lxc/src/lxc/lxccontainer.c:598:1
2021-04-17T10:31:53.1225421Z     #6 0x559e30123cb4 in main /home/runner/work/lxc/lxc/src/tests/console_log.c:104:8
2021-04-17T10:31:53.1227014Z     #7 0x7ff07f5620b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
2021-04-17T10:31:53.1227687Z 
2021-04-17T10:31:53.1229295Z SUMMARY: AddressSanitizer: 48 byte(s) leaked in 1 allocation(s).
2021-04-17T10:31:53.1263604Z + fail 'lxc-tests: /usr/bin/lxc-test-console-log' /usr/bin/lxc-test-console-log /tmp/tmp.TIZPiR4RQb
2021-04-17T10:31:53.1265153Z + TEST_FAIL=2
```

**Comment by evverx** [comment]
I've rebased #3787 on top of the master brach and rerun the tests. It seems the leak is still there:
```
2021-04-17T17:14:15.0316875Z =================================================================
2021-04-17T17:14:15.0317356Z ==75608==ERROR: LeakSanitizer: detected memory leaks
2021-04-17T17:14:15.0317715Z 
2021-04-17T17:14:15.0318106Z Direct leak of 48 byte(s) in 1 object(s) allocated from:
2021-04-17T17:14:15.0319333Z     #0 0x5561f351d2b2 in calloc (/usr/bin/lxc-test-console-log+0x962b2)
2021-04-17T17:14:15.0320134Z     #1 0x7fbb473f31ab in lxc_cmd_rsp_recv /home/runner/work/lxc/lxc/src/lxc/commands.c:290:13
2021-04-17T17:14:15.0321065Z     #2 0x7fbb473e5dc7 in lxc_cmd /home/runner/work/lxc/lxc/src/lxc/commands.c:514:8
2021-04-17T17:14:15.0321875Z     #3 0x7fbb473ed3ed in lxc_cmd_console_log /home/runner/work/lxc/lxc/src/lxc/commands.c:1449:8
2021-04-17T17:14:15.0322776Z     #4 0x7fbb4755cdd2 in do_lxcapi_console_log /home/runner/work/lxc/lxc/src/lxc/lxccontainer.c:581:8
2021-04-17T17:14:15.0323694Z     #5 0x7fbb4752b217 in lxcapi_console_log /home/runner/work/lxc/lxc/src/lxc/lxccontainer.c:598:1
2021-04-17T17:14:15.0324521Z     #6 0x5561f3546cb4 in main /home/runner/work/lxc/lxc/src/tests/console_log.c:104:8
2021-04-17T17:14:15.0325502Z     #7 0x7fbb478f80b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
2021-04-17T17:14:15.0325978Z 
2021-04-17T17:14:15.0326531Z SUMMARY: AddressSanitizer: 48 byte(s) leaked in 1 allocation(s).
```
