### ISSUE TITLE
Segmentation fault on restoring container

### ISSUE THREAD

**Issue by n-eiling** [lxc/lxc#907]
When I try to restore a container I get a segmentation fault.
My host system is a fedora 23 (4.4.4-301.fc23.x86_64)
I used the following command:
```
# lxc-checkpoint -n fed-test -r -D /tmp/ckp/ --logpriority=TRACE -o /tmp/ckp.log -F
Segmentation fault (core dumped)
```
(If I omit the -F I don't get any output)
The logfile only contains the following:

```
lxc-checkpoint 20160322154018.231 WARN     lxc_confile - confile.c:config_pivotdir:1859 - lxc.pivotdir is ignored.  It will soon become an error.
```

Debuggin with gdb results in the following backtrace:
```
#0  0x00007ffff71bb933 in vfprintf () from /lib64/libc.so.6
#1  0x00007ffff71e70c9 in vsnprintf () from /lib64/libc.so.6
#2  0x00007ffff71c3dc2 in snprintf () from /lib64/libc.so.6
#3  0x00007ffff7b760bb in fill_sock_name (path=path@entry=0x7fffff7ff821 "", 
    name=name@entry=0x603390 "fed-test", 
    lxcpath=lxcpath@entry=0x603350 "/global/cluster/libvirt-1.2.16-lxctools-f23/var/lib/lxc", hashed_sock_name=hashed_sock_name@entry=0x0, len=106) at commands.c:102
#4  0x00007ffff7b762e9 in lxc_cmd (name=name@entry=0x603390 "fed-test", 
    cmd=cmd@entry=0x7fffff7ff900, stopped=stopped@entry=0x7fffff7ff8dc, 
    lxcpath=lxcpath@entry=0x603350 "/global/cluster/libvirt-1.2.16-lxctools-f23/var/lib/lxc", hashed_sock_name=hashed_sock_name@entry=0x0) at commands.c:288
#5  0x00007ffff7b76b49 in lxc_cmd_get_cgroup_path (
    name=name@entry=0x603390 "fed-test", 
    lxcpath=lxcpath@entry=0x603350 "/global/cluster/libvirt-1.2.16-lxctools-f23/var/lib/lxc", subsystem=subsystem@entry=0x7fffff7ff940 "freezer") at commands.c:456
#6  0x00007ffff7b88c1c in cgfsng_get (filename=0x7ffff7bbe4c0 "freezer.state", 
    value=0x7fffff7ff9b0 "0\372\177\377\377\177", len=100, name=0x603390 "fed-test", 
    lxcpath=0x603350 "/global/cluster/libvirt-1.2.16-lxctools-f23/var/lib/lxc")
    at cgfsng.c:1582
#7  0x00007ffff7b7f0bf in freezer_state (name=name@entry=0x603390 "fed-test", 
    lxcpath=lxcpath@entry=0x603350 "/global/cluster/libvirt-1.2.16-lxctools-f23/var/lib/lxc") at freezer.c:45
#8  0x00007ffff7ba1651 in lxc_getstate (name=0x603390 "fed-test", 
    lxcpath=0x603350 "/global/cluster/libvirt-1.2.16-lxctools-f23/var/lib/lxc")
    at state.c:74
#9  0x00007ffff7baef75 in do_lxcapi_state (c=<optimized out>) at lxccontainer.c:423
#10 do_lxcapi_is_running (c=<optimized out>) at lxccontainer.c:442
...
```

My lxc & criu versions:
```
lxc-checkpoint --version
2.0.0.rc12
criu --version
Version: 2.0
GitID: v2.0
```

The container config:
```
# Distribution configuration
lxc.include = /global/cluster/libvirt-1.2.16-lxctools-f23/share/lxc/config/fedora.common.conf
lxc.arch = x86_64

# Container specific configuration
lxc.rootfs = /global/cluster/libvirt-1.2.16-lxctools-f23/var/lib/lxc/fed-test/rootfs
lxc.utsname = fed-test

# using either of these does not help
lxc.tty = 0
#lxc.cgroup.devices.deny = c 5:1 rwm
lxc.console = none
#lxc.seccomp =

# Network configuration
lxc.network.type = veth
lxc.network.link = br0
lxc.network.flags = up
lxc.network.hwaddr = 00:16:3e:77:d8:55


```

**Comment by tych0** [comment]
Can you please post the full backtrace?

**Comment by n-eiling** [comment]
Well the backtrace repeats itself. I uploaded the first ~14k lines... I hope that helps.

[backtrace](https://github.com/lxc/lxc/files/184350/gdb.txt)

**Comment by tych0** [comment]
Ah, d'oh. I think this is a linking issue; liblxc has a symbol called restore, and so does lxc-checkpoint. The call pattern here looks like it's calling the lxc-checkpoint's restore instead of liblxc's restore where it should be. I'll see about posting a patch.

**Comment by n-eiling** [comment]
Your patch fixed the problem. Thank you for the quick response!

**Comment by tych0** [comment]
No problem, thanks for the report!
